# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-92d04e27-64d5-4955-a370-0cef7842e5d3";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-92d04e27-64d5-4955-a370-0cef7842e5d3".device = "/dev/disk/by-uuid/92d04e27-64d5-4955-a370-0cef7842e5d3";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8A22-9A36";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-8f577fbc-07bb-4493-bb6f-f859a3ea6682"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
